### ISSUE TITLE
How to use the HSNE interpolation and project scale?

### ISSUE THREAD

**Issue by wilsonjr** [biovault/nptsne#10]
Hi, I was reading the HSNE article.

1. How can I use the library to generate an interpolation based on a hierarchy level?
2. How can I project an HSNE scale to plot, for example, using pyplot?

Thank you!

**Comment by bldrvnlw** [comment]
Hi there,

Something that you may find useful is the updated demo software - you can find that at  https://doi.org/10.5281/zenodo.4003502 in a single zip including the demo data. 

To answer your questions :

1. I'm not quite sure what you mean by "interpolation" but I'm assuming you mean drilling down to the original data from landmarks. If you look at the simplest demo of HSNE, that's the  **HSNELouvainDemo,** you see that an HSNE hierarchy is generated and then the top level plotted using networkx spring layout and clustered with Louvain clustering. The points you see are of course landmarks and represent multiple actual data points which you will need to retrieve to see what original data is being referred to. 

1a. If you want to see how that is achieved look at the other demo (**ExtendedHSNEDemo**) and you see in the _AnalysisController_ (which handles the signals from user interaction) that based on selected landmarks the Area of Influence can be recovered using a call to **analysis.get_area_of_influence(landmark_indexes)**

2. A mentioned above networkx spring plots are one possible way to plot an HSNE level. However this tends to be slow. More generally we use (Sparse) tSNE to create an embedding from the HSNE layer. This works well for a _few thousand points_;  of course with TextureTsne you can embed 10^5 points but the problem is interactive plotting - in other software that is solved using OpenGL to do the plotting. In the **ExtendedHSNEDemo** the embedding is displayed using matplotlib in the _EmbeddingGui_ display widget. The widget is so constructed that the evolving tSNE embedding is shown (by repeated calls to update_plot)  rather than just displaying the end result. Note though that matplotlib is too slow for really large interactive plots: 5x10^4 and more points, in general with HSNE you don't need this level of detail in the interactive plot to make useful selections. The landmarks are a good representation of the underlying data. The demos are usually limited to about 5000 landmark points at each level, well withing th capability of matplotlib.

Hope that helps

**Comment by wilsonjr** [comment]
Hello!
Thank you for your quick response!
I will try to use your suggestions to solve my problem.

However, by interpolation I mean to generate the complete embedding using the landmarks. In the HSNE paper, the authors show a way to generate the complete embedding based on a HSNE scale.

Is this feature implemented? Thank you!
