### ISSUE TITLE
Which type of initialization does HSNE use?

### ISSUE THREAD

**Issue by wilsonjr** [biovault/nptsne#12]
Hi, 
I was looking in the code to check how does HSNE initialize embeddings for dimensionality reduction.

I understand that t-SNE is used at the end of the day but which type of initialization does it use? PCA, random?

Checking the outputs and code I believe it is not random. Am I right?

**Comment by bldrvnlw** [comment]
HSNE discovers a hierarchy of landmarks in the knn-graph (see paper section 3 https://graphics.tudelft.nl/Publications-new/2016/PHLEV16/hsne.pdf). Each level in the hierarchy (or a sub-set thereof) can be displayed as a tSNE embedding. In our tSNE implementation the embedding is initialized randomly.  

If you wished you could employ an alternative dimensionality reduction algorithm (or different tSNE implementation) to create the embedding. The is no fixed coupling between the two algorithms (HNSE & tSNE) in nptsne, but the demo code does use tSNE as described in the HSNE paper: To quote:  _**we rely on tSNE because of its ability to overcome the so called crowding problem**_ 

Hope that helps.

**Comment by wilsonjr** [comment]
It helps a lot. Thank you!
